#!/bin/sh
#
# Copyright (C) 2018 Reto Schneider (code@reto-schneider.ch)
#

uci -q batch <<-EOF >/dev/null
  delete dhcp.lan

  set dhcp.dhcpd='dnsmasq'
  set dhcp.dhcpd.port='0'
  set dhcp.dhcpd.nonwildcard='1'

  set dhcp.dns='dnsmasq'
  set dhcp.dns.port='0'
  set dhcp.dns.nonwildcard='1'

  set dhcp.wifi='dhcp'
  set dhcp.wifi.interface='wifi'
  set dhcp.wifi.instance='dhcpd'
  set dhcp.wifi.start='100'
  set dhcp.wifi.limit='100'
  set dhcp.wifi.dhcpv6='disabled'
  set dhcp.wifi.ra='disabled'

  commit dhcp
EOF

exit 0
