#!/bin/sh
#
# Copyright (C) 2018 Reto Schneider (code@reto-schneider.ch)
#
# Enable WAN LED on link, blink on activity

# The lan LED of the GL-MT300A can not be turned off. Also, lan and wan LED are
# swaped compared to the GL-AR150. This needs to be fixed upstream.
readonly board_name=$(cat /tmp/sysinfo/board_name)
case ${board_name} in
  gl-ar150)
    readonly led=wan
    ;;
  *)
    echo Unsupported board: ${board_name} >&2
    exit 1
    ;;
esac

uci set system.wan_led=led
uci set system.wan_led.sysfs=${board_name}:${led}
uci set system.wan_led.name='WAN'
uci set system.wan_led.trigger='netdev'
uci set system.wan_led.dev='eth0'
uci set system.wan_led.mode='link tx rx'

uci commit system

exit 0
