#!/bin/sh
#
# Copyright (C) 2018 Reto Schneider (code@reto-schneider.ch)
#

uci -q batch <<-EOF >/dev/null
  set wireless.radio0.disabled='0'
  set wireless.radio0.country='CH'
  set wireless.radio0.txpower='18'

  set wireless.default_radio0.ssid='#CHFreeWiFi'
  set wireless.default_radio0.isolate='1'
  set wireless.default_radio0.network='wifi'

  commit wireless
EOF

exit 0
